//! Versioned JSONL schema for persisted translation sessions.
//!
//! Each session log is newline-delimited JSON.  The first line is a
//! [`SessionLogRecord::SessionHeader`] and each later subtitle entry is a
//! [`SessionLogRecord::TranscriptSegment`].  Every record carries
//! [`SESSION_LOG_SCHEMA_VERSION`] so replay/export code can reject or migrate
//! future formats explicitly instead of guessing.
//!
//! Versioning rules:
//! - Additive optional fields keep the same major schema version.
//! - Renaming, removing, or changing the meaning of a required field requires a
//!   new schema version and a migration path.
//! - Readers must reject records with versions greater than
//!   [`SESSION_LOG_SCHEMA_VERSION`] until a migration is implemented.

#![allow(dead_code)]

/// HC-03: session recorder supervisor stub (classification is in crate::config::recorder_supervisor).
pub mod supervisor;

pub mod export;
#[allow(unused_imports)]
pub use export::{export_srt, export_txt, transcript_segments_from_jsonl, SessionExportError};

pub mod pairing;
#[allow(unused_imports)]
pub(crate) use pairing::looks_like_segment_stem;
#[allow(unused_imports)]
pub use pairing::{check_session_pairing, session_id_from_jsonl_path, SessionPairingError};

pub mod replay;
#[allow(unused_imports)]
pub use replay::{transcript_segments_from_jsonl_lenient, SessionReplayError, SessionReplayer};

use serde::{Deserialize, Deserializer, Serialize};
use std::{
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    time::{SystemTime, UNIX_EPOCH},
};
use thiserror::Error;
use tokio::{
    fs::{self, File, OpenOptions},
    io::AsyncWriteExt,
    sync::{mpsc, oneshot},
    task::JoinHandle,
};

/// Current JSONL session-log schema version.
pub const SESSION_LOG_SCHEMA_VERSION: u16 = 1;

const RECORDER_QUEUE_CAPACITY: usize = 64;

/// Internal writer message — either a JSONL record or a lifecycle command.
enum WriterMessage {
    /// A normal record to append to the JSONL file.
    Record(SessionLogRecord),
    /// Seal the current JSONL file and open a new one at `new_session_dir`.
    ///
    /// The writer task flushes the current file, creates `new_session_dir` if
    /// needed, opens `new_session_dir/00001.jsonl`, writes `new_header` as the
    /// first record, and sends the new path on `done_tx`.
    SealAndReopen {
        /// Directory for the new session's JSONL segments.
        new_session_dir: PathBuf,
        /// Session header to write as the first record of the new file.
        new_header: SessionHeader,
        /// Notified with `Ok(new_path)` on success or `Err(msg)` on failure.
        done_tx: oneshot::Sender<Result<PathBuf, String>>,
    },
}

/// A single line in a persisted session JSONL file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "record_type", rename_all = "snake_case")]
pub enum SessionLogRecord {
    /// File/session metadata.  This must be the first record in a new log.
    SessionHeader(SessionHeader),
    /// One committed bilingual subtitle segment.
    TranscriptSegment(TranscriptSegment),
}

impl SessionLogRecord {
    /// Return the schema version carried by this record.
    pub fn schema_version(&self) -> u16 {
        match self {
            Self::SessionHeader(header) => header.schema_version,
            Self::TranscriptSegment(segment) => segment.schema_version,
        }
    }
}

/// Metadata that describes one translation session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionHeader {
    /// Schema version used by every record in this file.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Stable opaque session identifier generated by the writer.
    pub session_id: String,
    /// Application version that created the session log.
    pub app_version: String,
    /// Unix timestamp in milliseconds when capture started.
    pub started_at_unix_ms: u64,
    /// Source language spoken in the meeting, as a BCP-47 tag.
    pub source_language: String,
    /// Target subtitle language, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider selected for this session.
    pub stt_provider: String,
    /// Machine-translation provider selected for this session.
    pub mt_provider: String,
    /// Whether translated audio playback was enabled at session start.
    pub tts_enabled: bool,
    /// Capture device label if one was selected; absent means Windows default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capture_device: Option<String>,
    /// Human-readable slot label for dual-slot sessions ("A" for slot A, "B" for slot B).
    /// Absent in single-slot sessions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slot_label: Option<String>,
    /// Machine-readable slot identifier for dual-slot sessions.
    ///
    /// This matches the lowercase filename suffix used by the recorder
    /// (for example, built-in dual mode uses `"a"` and `"b"`).
    /// Absent in single-slot sessions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slot_id: Option<String>,
}

/// One committed bilingual subtitle segment and its replay/export metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TranscriptSegment {
    /// Schema version used by this segment.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Session identifier matching the header record.
    pub session_id: String,
    /// Monotonic segment identifier assigned after final subtitle promotion.
    pub segment_id: u64,
    /// Pipeline sequence number for the STT audio window or streaming segment.
    pub sequence_number: u64,
    /// Unix timestamp in milliseconds when the source text became final.
    pub finalized_at_unix_ms: u64,
    /// Start of the source audio span relative to session start, in milliseconds.
    pub audio_start_ms: u64,
    /// End of the source audio span relative to session start, in milliseconds.
    pub audio_end_ms: u64,
    /// Recognized source-language text.
    pub source_text: String,
    /// Translated target-language text.
    pub target_text: String,
    /// Source language for this segment, as a BCP-47 tag.
    pub source_language: String,
    /// Source language detected by the MT provider, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detected_source_language: Option<String>,
    /// Target language for this segment, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider that produced `source_text`.
    pub stt_provider: String,
    /// Machine-translation provider that produced `target_text`.
    pub mt_provider: String,
    /// STT confidence in the range `[0.0, 1.0]`, when provided by the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_confidence: Option<f32>,
    /// STT final/interim flag captured for audit and replay diagnostics.
    pub stt_is_final: bool,
    /// STT latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_latency_ms: Option<u64>,
    /// Machine-translation latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mt_latency_ms: Option<u64>,
    /// End-to-end latency from audio submission to translated subtitle display.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_to_end_latency_ms: Option<u64>,
    /// Cumulative audio seconds sent to STT when this segment was committed.
    pub audio_seconds_sent: f64,
    /// Cumulative source characters sent to MT when this segment was committed.
    pub chars_translated: u64,
    /// Estimated cumulative cost in USD when this segment was committed.
    pub estimated_cost_usd: f64,
}

/// Return `true` when `version` can be read by this binary without migration.
pub fn is_supported_schema_version(version: u16) -> bool {
    version != 0 && version <= SESSION_LOG_SCHEMA_VERSION
}

/// Convert a [`SystemTime`] to Unix milliseconds, saturating at zero before the epoch.
pub fn system_time_unix_ms(time: SystemTime) -> u64 {
    time.duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().min(u128::from(u64::MAX)) as u64)
        .unwrap_or(0)
}

/// Generate an opaque session id safe for use as a log-file stem.
pub fn generate_session_id(started_at_unix_ms: u64) -> String {
    format!("session-{started_at_unix_ms}-{}", std::process::id())
}

/// Runtime configuration for transcript session recording.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionRecorderConfig {
    /// Whether transcript JSONL recording is enabled.
    pub enabled: bool,
    /// Parent directory under which per-session subdirectories
    /// (`<directory>/<session-id>/<segment>.jsonl`) are written.
    pub directory: PathBuf,
    /// Maximum number of session directories to keep, including the new one.
    pub max_sessions: Option<usize>,
    /// LF-06 per-session byte cap.  When the active segment file exceeds this
    /// many bytes, the writer task seals it and starts a new segment under
    /// the same session directory.  `0` disables segment rollover.
    pub per_session_bytes_cap: u64,
    /// Optional slot suffix appended to segment file names for dual-slot sessions
    /// (e.g. `"a"` → `00001-a.jsonl`, `"b"` → `00001-b.jsonl`).
    /// `None` (default) produces standard `00001.jsonl` segments.
    pub slot_suffix: Option<String>,
}

impl SessionRecorderConfig {
    /// Create an enabled recorder config using `directory`.
    pub fn enabled(directory: impl Into<PathBuf>) -> Self {
        Self {
            enabled: true,
            directory: directory.into(),
            max_sessions: None,
            per_session_bytes_cap: 0,
            slot_suffix: None,
        }
    }

    /// Create an enabled recorder config and cap retained sessions.
    pub fn enabled_with_max_sessions(directory: impl Into<PathBuf>, max_sessions: usize) -> Self {
        Self {
            enabled: true,
            directory: directory.into(),
            max_sessions: Some(max_sessions),
            per_session_bytes_cap: 0,
            slot_suffix: None,
        }
    }

    /// Builder: set the per-session byte cap for segment rollover.
    pub fn with_per_session_bytes_cap(mut self, cap: u64) -> Self {
        self.per_session_bytes_cap = cap;
        self
    }

    /// Builder: set the slot suffix for dual-slot sessions.
    ///
    /// Suffix must be 1–8 ASCII alphanumeric characters (e.g. `"a"`, `"b"`).
    /// Produces segment files like `00001-a.jsonl` instead of `00001.jsonl`.
    ///
    /// # Errors
    ///
    /// Returns an error if the suffix contains path-traversal characters or
    /// is otherwise unsafe to use as a file-name component.
    pub fn with_slot_suffix(mut self, suffix: impl Into<String>) -> anyhow::Result<Self> {
        let suffix = suffix.into();
        validate_slot_suffix(&suffix)?;
        self.slot_suffix = Some(suffix);
        Ok(self)
    }

    /// Create a disabled recorder config. The directory is kept for tests and diagnostics.
    pub fn disabled(directory: impl Into<PathBuf>) -> Self {
        Self {
            enabled: false,
            directory: directory.into(),
            max_sessions: None,
            per_session_bytes_cap: 0,
            slot_suffix: None,
        }
    }
}

/// Non-blocking transcript JSONL recorder.
///
/// The hot path calls [`record_segment`](Self::record_segment), which uses
/// `try_send` into a bounded channel. Disk I/O runs on a Tokio task and writes
/// each line through the Tokio file handle; this is not an fsync durability
/// guarantee.
///
/// HC-03: [`seal_and_reopen`](Self::seal_and_reopen) flushes the current JSONL
/// file and opens a new one at a different path without consuming `self` — safe
/// to call while `OrchestratorContext` owns the recorder by value.
pub struct SessionRecorder {
    session_id: Option<String>,
    session_dir: Option<PathBuf>,
    active_path: Arc<Mutex<Option<PathBuf>>>,
    sender: Option<mpsc::Sender<WriterMessage>>,
    writer: Option<JoinHandle<()>>,
    last_error: Arc<Mutex<Option<String>>>,
    /// Monotonically non-decreasing count of bytes successfully handed to the
    /// OS for the JSONL file since the recorder was started (including the
    /// header line). Zero when the recorder is disabled.
    bytes_written: Arc<AtomicU64>,
}

impl SessionRecorder {
    /// Return a recorder that never creates files and ignores segments.
    pub fn disabled() -> Self {
        Self {
            session_id: None,
            session_dir: None,
            active_path: Arc::new(Mutex::new(None)),
            sender: None,
            writer: None,
            last_error: Arc::new(Mutex::new(None)),
            bytes_written: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Start a recorder and write the header line before returning.
    pub async fn start(
        config: SessionRecorderConfig,
        header: SessionHeader,
    ) -> anyhow::Result<Self> {
        if !config.enabled {
            return Ok(Self::disabled());
        }

        fs::create_dir_all(&config.directory).await.map_err(|err| {
            anyhow::anyhow!(
                "failed to create session directory {}: {err}",
                config.directory.display()
            )
        })?;
        if let Some(max_sessions) = config.max_sessions {
            prune_session_dirs(&config.directory, max_sessions)?;
        }

        // LF-06: validate the session-id as a path component; fall back to the
        // legacy filesystem sanitizer when the caller supplied a string with
        // non-component characters so existing flows keep working.
        let session_subdir_name = if is_valid_path_component(&header.session_id) {
            header.session_id.clone()
        } else {
            sanitize_session_id_for_fs(&header.session_id)
        };

        let session_dir = config.directory.join(&session_subdir_name);
        fs::create_dir_all(&session_dir).await.map_err(|err| {
            anyhow::anyhow!(
                "failed to create per-session directory {}: {err}",
                session_dir.display()
            )
        })?;

        let path = session_dir.join(segment_file_name(1, config.slot_suffix.as_deref()));
        let session_id = header.session_id.clone();
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
            .await
            .map_err(|err| {
                anyhow::anyhow!("failed to create session log {}: {err}", path.display())
            })?;

        let header_record = SessionLogRecord::SessionHeader(header);
        let header_byte_count =
            write_record_line(&mut file, &header_record)
                .await
                .map_err(|err| {
                    anyhow::anyhow!("failed to write session header {}: {err}", path.display())
                })?;

        let bytes_written = Arc::new(AtomicU64::new(header_byte_count as u64));
        let active_path = Arc::new(Mutex::new(Some(path.clone())));

        let (tx, rx) = mpsc::channel(RECORDER_QUEUE_CAPACITY);
        let last_error = Arc::new(Mutex::new(None));
        let writer = tokio::spawn(run_writer(
            file,
            rx,
            WriterRuntime {
                last_error: Arc::clone(&last_error),
                session_dir: session_dir.clone(),
                active_path: Arc::clone(&active_path),
                initial_segment_bytes: header_byte_count as u64,
                per_session_bytes_cap: config.per_session_bytes_cap,
                bytes_written: Arc::clone(&bytes_written),
                slot_suffix: config.slot_suffix,
            },
        ));

        Ok(Self {
            session_id: Some(session_id),
            session_dir: Some(session_dir),
            active_path,
            sender: Some(tx),
            writer: Some(writer),
            last_error,
            bytes_written,
        })
    }

    /// Return the active JSONL segment path when recording is enabled.
    pub fn path(&self) -> Option<PathBuf> {
        self.active_path
            .lock()
            .unwrap_or_else(|p| p.into_inner())
            .clone()
    }

    /// Return the per-session directory that holds JSONL segments.
    pub fn session_dir(&self) -> Option<&Path> {
        self.session_dir.as_deref()
    }

    /// Return the active session id when recording is enabled.
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Return `true` when this recorder writes transcript files.
    pub fn is_enabled(&self) -> bool {
        self.sender.is_some()
    }

    /// Total bytes successfully handed to the OS for the JSONL file since the
    /// recorder started, including the session header.  Monotonically non-decreasing
    /// within a session.  Returns `0` when the recorder is disabled or before
    /// the first write completes.
    pub fn bytes_written(&self) -> u64 {
        self.bytes_written.load(Ordering::Relaxed)
    }

    /// Shared atomic handle for the bytes-written counter.
    ///
    /// Callers that outlive the [`SessionRecorder`] (e.g. the metrics-publisher
    /// task) should clone this `Arc` before the recorder is moved elsewhere.
    pub fn bytes_written_arc(&self) -> Arc<AtomicU64> {
        Arc::clone(&self.bytes_written)
    }

    /// Queue one final transcript segment without waiting for disk I/O.
    pub fn record_segment(&self, segment: TranscriptSegment) -> Result<(), SessionRecorderError> {
        let Some(sender) = &self.sender else {
            return Ok(());
        };

        if let Some(message) = self.last_error() {
            return Err(SessionRecorderError::WriterStopped(message));
        }

        let segment_id = segment.segment_id;
        match sender.try_send(WriterMessage::Record(SessionLogRecord::TranscriptSegment(
            segment,
        ))) {
            Ok(()) => Ok(()),
            Err(mpsc::error::TrySendError::Full(_)) => {
                Err(SessionRecorderError::QueueFull { segment_id })
            }
            Err(mpsc::error::TrySendError::Closed(_)) => Err(SessionRecorderError::WriterStopped(
                self.last_error()
                    .unwrap_or_else(|| "session recorder writer stopped".to_string()),
            )),
        }
    }

    /// Return the last asynchronous writer error, if any.
    pub fn last_error(&self) -> Option<String> {
        self.last_error
            .lock()
            .unwrap_or_else(|p| p.into_inner())
            .clone()
    }

    /// Seal the current JSONL segment and open a new one at `new_session_dir`.
    ///
    /// The writer task:
    /// 1. Flushes the active segment file (making it parseable through the last
    ///    line written).
    /// 2. Creates `new_session_dir` if it does not exist.
    /// 3. Opens `new_session_dir/00001.jsonl` (fails with `WriterStopped` when
    ///    that file already exists).
    /// 4. Writes `new_header` as the first JSONL line of the new file.
    /// 5. Returns the new file path on `Ok`.
    ///
    /// The recorder continues to accept [`record_segment`](Self::record_segment)
    /// calls. Records that the writer processes before the seal message stay
    /// in the old file; records submitted after this method returns are written
    /// to the new file. Callers that need strict old/new ordering must await
    /// this method before queueing records for the new session.
    ///
    /// Does nothing and returns `Err(WriterStopped)` when the recorder is
    /// disabled.
    ///
    /// # HC-03 note
    ///
    /// This method does not consume `self`, so it is safe to call while
    /// `OrchestratorContext` owns the recorder by value.
    pub async fn seal_and_reopen(
        &mut self,
        new_session_dir: PathBuf,
        new_header: SessionHeader,
    ) -> Result<PathBuf, SessionRecorderError> {
        let Some(sender) = &self.sender else {
            return Err(SessionRecorderError::WriterStopped(
                "recorder is disabled".to_string(),
            ));
        };
        let new_session_id = new_header.session_id.clone();
        let (done_tx, done_rx) = oneshot::channel();
        sender
            .send(WriterMessage::SealAndReopen {
                new_session_dir: new_session_dir.clone(),
                new_header,
                done_tx,
            })
            .await
            .map_err(|_| {
                SessionRecorderError::WriterStopped("writer channel closed".to_string())
            })?;
        match done_rx.await {
            Ok(Ok(new_path)) => {
                // Update the recorder's session_dir so path() / session_dir()
                // / session_id() reflect the new location.
                self.session_dir = Some(new_session_dir);
                self.session_id = Some(new_session_id);
                Ok(new_path)
            }
            Ok(Err(msg)) => Err(SessionRecorderError::WriterStopped(msg)),
            Err(_) => Err(SessionRecorderError::WriterStopped(
                "writer did not confirm seal".to_string(),
            )),
        }
    }

    /// Drop the sender and wait for the writer task to flush all queued records.
    pub async fn shutdown(mut self) -> Result<(), SessionRecorderError> {
        drop(self.sender.take());
        if let Some(writer) = self.writer.take() {
            writer
                .await
                .map_err(|err| SessionRecorderError::WriterStopped(err.to_string()))?;
        }
        if let Some(message) = self.last_error() {
            Err(SessionRecorderError::WriterStopped(message))
        } else {
            Ok(())
        }
    }
}

/// Errors surfaced synchronously from the non-blocking recorder handle.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SessionRecorderError {
    /// The bounded writer queue is full; this segment was dropped.
    #[error("session recorder queue is full; dropped transcript segment {segment_id}")]
    QueueFull {
        /// Segment that could not be queued.
        segment_id: u64,
    },
    /// The writer task has stopped, usually after a disk I/O error.
    #[error("session recorder writer stopped: {0}")]
    WriterStopped(String),
}

struct WriterRuntime {
    last_error: Arc<Mutex<Option<String>>>,
    session_dir: PathBuf,
    active_path: Arc<Mutex<Option<PathBuf>>>,
    initial_segment_bytes: u64,
    per_session_bytes_cap: u64,
    bytes_written: Arc<AtomicU64>,
    slot_suffix: Option<String>,
}

async fn run_writer(mut file: File, mut rx: mpsc::Receiver<WriterMessage>, writer: WriterRuntime) {
    let WriterRuntime {
        last_error,
        mut session_dir,
        active_path,
        initial_segment_bytes,
        per_session_bytes_cap,
        bytes_written,
        slot_suffix,
    } = writer;
    let mut current_segment: u32 = 1;
    let mut current_segment_bytes: u64 = initial_segment_bytes;
    let mut current_path: PathBuf = active_path
        .lock()
        .unwrap_or_else(|p| p.into_inner())
        .clone()
        .unwrap_or_else(|| {
            session_dir.join(segment_file_name(current_segment, slot_suffix.as_deref()))
        });

    while let Some(msg) = rx.recv().await {
        let record = match msg {
            WriterMessage::Record(r) => r,
            WriterMessage::SealAndReopen {
                new_session_dir,
                new_header,
                done_tx,
            } => {
                // Flush the current file so it is fully parseable.
                if let Err(err) = file.flush().await {
                    let m = format!("seal: flush failed for {}: {err}", current_path.display());
                    tracing::warn!("{m}");
                    let _ = done_tx.send(Err(m));
                    continue;
                }
                // Create new session directory.
                if let Err(err) = fs::create_dir_all(&new_session_dir).await {
                    let m = format!(
                        "seal: cannot create session dir {}: {err}",
                        new_session_dir.display()
                    );
                    tracing::warn!("{m}");
                    let _ = done_tx.send(Err(m));
                    continue;
                }
                let new_path = new_session_dir.join(segment_file_name(1, slot_suffix.as_deref()));
                match OpenOptions::new()
                    .write(true)
                    .create_new(true)
                    .open(&new_path)
                    .await
                {
                    Ok(mut new_file) => {
                        let header_record = SessionLogRecord::SessionHeader(new_header);
                        match write_record_line(&mut new_file, &header_record).await {
                            Ok(header_bytes) => {
                                file = new_file;
                                session_dir = new_session_dir;
                                current_segment = 1;
                                current_segment_bytes = header_bytes as u64;
                                current_path = new_path.clone();
                                *active_path.lock().unwrap_or_else(|p| p.into_inner()) =
                                    Some(new_path.clone());
                                tracing::info!(
                                    path = %new_path.display(),
                                    "recorder sealed and reopened at new path"
                                );
                                let _ = done_tx.send(Ok(new_path));
                            }
                            Err(err) => {
                                let m = format!(
                                    "seal: write header failed for {}: {err}",
                                    new_path.display()
                                );
                                tracing::warn!("{m}");
                                let _ = done_tx.send(Err(m));
                            }
                        }
                    }
                    Err(err) => {
                        let m = format!("seal: cannot open new file {}: {err}", new_path.display());
                        tracing::warn!("{m}");
                        let _ = done_tx.send(Err(m));
                    }
                }
                continue;
            }
        };
        // Pre-serialise to know the line length so we can rotate before writing.
        let line = match serialise_record_line(&record) {
            Ok(line) => line,
            Err(err) => {
                let message = format!(
                    "session recorder serialise failed for {}: {err}",
                    current_path.display()
                );
                tracing::warn!("{message}");
                *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
                break;
            }
        };
        let line_len = line.len() as u64;

        if per_session_bytes_cap > 0
            && current_segment_bytes > 0
            && current_segment_bytes.saturating_add(line_len) > per_session_bytes_cap
        {
            if let Err(err) = file.flush().await {
                let message = format!(
                    "session recorder flush failed for {}: {err}",
                    current_path.display()
                );
                tracing::warn!("{message}");
                *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
                break;
            }
            current_segment = current_segment.saturating_add(1);
            let next_path =
                session_dir.join(segment_file_name(current_segment, slot_suffix.as_deref()));
            match OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&next_path)
                .await
            {
                Ok(next_file) => {
                    file = next_file;
                    current_path = next_path.clone();
                    *active_path.lock().unwrap_or_else(|p| p.into_inner()) = Some(next_path);
                    current_segment_bytes = 0;
                }
                Err(err) => {
                    let message = format!(
                        "session recorder failed to open next segment {}: {err}",
                        next_path.display()
                    );
                    tracing::warn!("{message}");
                    *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
                    break;
                }
            }
        }

        match write_line_bytes(&mut file, &line).await {
            Ok(()) => {
                current_segment_bytes = current_segment_bytes.saturating_add(line_len);
                bytes_written.fetch_add(line_len, Ordering::Relaxed);
            }
            Err(err) => {
                let message = format!(
                    "session recorder write failed for {}: {err}",
                    current_path.display()
                );
                tracing::warn!("{message}");
                *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
                break;
            }
        }
    }

    if let Err(err) = file.flush().await {
        let message = format!(
            "session recorder flush failed for {}: {err}",
            current_path.display()
        );
        tracing::warn!("{message}");
        *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
    }
}

fn serialise_record_line(record: &SessionLogRecord) -> std::io::Result<Vec<u8>> {
    let mut line = serde_json::to_vec(record).map_err(std::io::Error::other)?;
    line.push(b'\n');
    Ok(line)
}

async fn write_line_bytes(file: &mut File, line: &[u8]) -> std::io::Result<()> {
    file.write_all(line).await?;
    file.flush().await
}

async fn write_record_line(file: &mut File, record: &SessionLogRecord) -> std::io::Result<usize> {
    let line = serialise_record_line(record)?;
    let len = line.len();
    write_line_bytes(file, &line).await?;
    Ok(len)
}

fn segment_file_name(segment_index: u32, slot_suffix: Option<&str>) -> String {
    match slot_suffix {
        None => format!("{segment_index:05}.jsonl"),
        Some(s) => format!("{segment_index:05}-{s}.jsonl"),
    }
}

/// Validate a slot suffix to prevent path traversal and filesystem collisions.
///
/// A valid suffix is 1-8 lowercase ASCII alphanumeric characters (e.g. `"a"`, `"b"`).
fn validate_slot_suffix(suffix: &str) -> anyhow::Result<()> {
    if suffix.is_empty() {
        anyhow::bail!("slot suffix must not be empty");
    }
    if suffix.len() > 8 {
        anyhow::bail!("slot suffix too long (max 8 chars): {suffix:?}");
    }
    if !suffix
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
    {
        anyhow::bail!(
            "slot suffix must contain only lowercase ASCII alphanumeric characters: {suffix:?}"
        );
    }
    Ok(())
}

fn sanitize_session_id_for_fs(session_id: &str) -> String {
    session_id
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

/// Local mirror of `storage::validate_path_component`'s acceptance rule —
/// duplicated so that bin targets which only pull in `session/mod.rs`
/// (e.g. `eval_session`) still build without a separate `storage` mount.
/// The rule must stay in sync with `crate::storage::validate_path_component`.
fn is_valid_path_component(component: &str) -> bool {
    if component.is_empty() || component == "." || component == ".." {
        return false;
    }
    if component.contains('/') || component.contains('\\') || component.contains(':') {
        return false;
    }
    if component.chars().any(|c| {
        (c as u32) < 0x20 || c == '<' || c == '>' || c == '"' || c == '|' || c == '?' || c == '*'
    }) {
        return false;
    }
    if component.ends_with('.') || component.ends_with(' ') {
        return false;
    }
    // Reject absolute path / drive prefix.
    if std::path::Path::new(component).is_absolute() {
        return false;
    }
    // Reject Windows reserved device names (case-insensitive, base stem).
    let stem = component
        .split('.')
        .next()
        .unwrap_or(component)
        .to_ascii_uppercase();
    !matches!(
        stem.as_str(),
        "CON"
            | "PRN"
            | "AUX"
            | "NUL"
            | "COM1"
            | "COM2"
            | "COM3"
            | "COM4"
            | "COM5"
            | "COM6"
            | "COM7"
            | "COM8"
            | "COM9"
            | "LPT1"
            | "LPT2"
            | "LPT3"
            | "LPT4"
            | "LPT5"
            | "LPT6"
            | "LPT7"
            | "LPT8"
            | "LPT9"
    )
}

#[allow(dead_code)]
fn session_log_file_name(session_id: &str) -> String {
    format!("{}.jsonl", sanitize_session_id_for_fs(session_id))
}

struct SessionLogCandidate {
    path: PathBuf,
    modified: SystemTime,
}

fn prune_session_dirs(directory: &Path, max_sessions: usize) -> anyhow::Result<()> {
    if max_sessions == 0 {
        anyhow::bail!("session recorder max_sessions must be greater than zero");
    }

    let keep_existing = max_sessions.saturating_sub(1);
    let mut entries = Vec::new();
    let read = match std::fs::read_dir(directory) {
        Ok(rd) => rd,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => {
            return Err(anyhow::anyhow!(
                "failed to read session directory {}: {err}",
                directory.display()
            ));
        }
    };
    for entry in read {
        let entry = entry.map_err(|err| {
            anyhow::anyhow!(
                "failed to read session directory entry {}: {err}",
                directory.display()
            )
        })?;
        let path = entry.path();
        let metadata = entry.metadata().map_err(|err| {
            anyhow::anyhow!("failed to inspect session entry {}: {err}", path.display())
        })?;
        // Per-session subdirectories (LF-06 layout) are the canonical units to
        // prune.  Legacy flat `*.jsonl` files are also considered so the count
        // cap remains correct during the migration window.
        let is_session_dir = metadata.is_dir();
        let is_legacy_log =
            metadata.is_file() && path.extension().and_then(|ext| ext.to_str()) == Some("jsonl");
        if !is_session_dir && !is_legacy_log {
            continue;
        }
        entries.push(SessionLogCandidate {
            path,
            modified: metadata.modified().unwrap_or(UNIX_EPOCH),
        });
    }

    if entries.len() <= keep_existing {
        return Ok(());
    }

    entries.sort_by(|a, b| {
        a.modified
            .cmp(&b.modified)
            .then_with(|| a.path.cmp(&b.path))
    });
    let remove_count = entries.len() - keep_existing;
    for candidate in entries.into_iter().take(remove_count) {
        let result = if candidate.path.is_dir() {
            std::fs::remove_dir_all(&candidate.path)
        } else {
            std::fs::remove_file(&candidate.path)
        };
        result.map_err(|err| {
            anyhow::anyhow!(
                "failed to prune old session entry {}: {err}",
                candidate.path.display()
            )
        })?;
    }
    Ok(())
}

fn deserialize_supported_schema_version<'de, D>(deserializer: D) -> Result<u16, D::Error>
where
    D: Deserializer<'de>,
{
    let version = u16::deserialize(deserializer)?;
    if is_supported_schema_version(version) {
        Ok(version)
    } else {
        Err(serde::de::Error::custom(format!(
            "unsupported session log schema version {version}; supported range is 1..={SESSION_LOG_SCHEMA_VERSION}"
        )))
    }
}

#[cfg(test)]
#[path = "recorder_tests.rs"]
mod recorder_tests;

#[cfg(test)]
#[path = "replayer_slot_tests.rs"]
mod replayer_slot_tests;
