//! Versioned JSONL schema for persisted translation sessions.
//!
//! Each session log is newline-delimited JSON.  The first line is a
//! [`SessionLogRecord::SessionHeader`] and each later subtitle entry is a
//! [`SessionLogRecord::TranscriptSegment`].  Every record carries
//! [`SESSION_LOG_SCHEMA_VERSION`] so replay/export code can reject or migrate
//! future formats explicitly instead of guessing.
//!
//! Versioning rules:
//! - Additive optional fields keep the same major schema version.
//! - Renaming, removing, or changing the meaning of a required field requires a
//!   new schema version and a migration path.
//! - Readers must reject records with versions greater than
//!   [`SESSION_LOG_SCHEMA_VERSION`] until a migration is implemented.

#![allow(dead_code)]

use serde::{Deserialize, Deserializer, Serialize};
use std::{
    collections::VecDeque,
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    time::{SystemTime, UNIX_EPOCH},
};
use thiserror::Error;
use tokio::{
    fs::{self, File, OpenOptions},
    io::AsyncWriteExt,
    sync::mpsc,
    task::JoinHandle,
};

/// Current JSONL session-log schema version.
pub const SESSION_LOG_SCHEMA_VERSION: u16 = 1;

const RECORDER_QUEUE_CAPACITY: usize = 64;

/// A single line in a persisted session JSONL file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "record_type", rename_all = "snake_case")]
pub enum SessionLogRecord {
    /// File/session metadata.  This must be the first record in a new log.
    SessionHeader(SessionHeader),
    /// One committed bilingual subtitle segment.
    TranscriptSegment(TranscriptSegment),
}

impl SessionLogRecord {
    /// Return the schema version carried by this record.
    pub fn schema_version(&self) -> u16 {
        match self {
            Self::SessionHeader(header) => header.schema_version,
            Self::TranscriptSegment(segment) => segment.schema_version,
        }
    }
}

/// Metadata that describes one translation session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionHeader {
    /// Schema version used by every record in this file.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Stable opaque session identifier generated by the writer.
    pub session_id: String,
    /// Application version that created the session log.
    pub app_version: String,
    /// Unix timestamp in milliseconds when capture started.
    pub started_at_unix_ms: u64,
    /// Source language spoken in the meeting, as a BCP-47 tag.
    pub source_language: String,
    /// Target subtitle language, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider selected for this session.
    pub stt_provider: String,
    /// Machine-translation provider selected for this session.
    pub mt_provider: String,
    /// Whether translated audio playback was enabled at session start.
    pub tts_enabled: bool,
    /// Capture device label if one was selected; absent means Windows default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capture_device: Option<String>,
}

/// One committed bilingual subtitle segment and its replay/export metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TranscriptSegment {
    /// Schema version used by this segment.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Session identifier matching the header record.
    pub session_id: String,
    /// Monotonic segment identifier assigned after final subtitle promotion.
    pub segment_id: u64,
    /// Pipeline sequence number for the STT audio window or streaming segment.
    pub sequence_number: u64,
    /// Unix timestamp in milliseconds when the source text became final.
    pub finalized_at_unix_ms: u64,
    /// Start of the source audio span relative to session start, in milliseconds.
    pub audio_start_ms: u64,
    /// End of the source audio span relative to session start, in milliseconds.
    pub audio_end_ms: u64,
    /// Recognized source-language text.
    pub source_text: String,
    /// Translated target-language text.
    pub target_text: String,
    /// Source language for this segment, as a BCP-47 tag.
    pub source_language: String,
    /// Source language detected by the MT provider, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detected_source_language: Option<String>,
    /// Target language for this segment, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider that produced `source_text`.
    pub stt_provider: String,
    /// Machine-translation provider that produced `target_text`.
    pub mt_provider: String,
    /// STT confidence in the range `[0.0, 1.0]`, when provided by the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_confidence: Option<f32>,
    /// STT final/interim flag captured for audit and replay diagnostics.
    pub stt_is_final: bool,
    /// STT latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_latency_ms: Option<u64>,
    /// Machine-translation latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mt_latency_ms: Option<u64>,
    /// End-to-end latency from audio submission to translated subtitle display.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_to_end_latency_ms: Option<u64>,
    /// Cumulative audio seconds sent to STT when this segment was committed.
    pub audio_seconds_sent: f64,
    /// Cumulative source characters sent to MT when this segment was committed.
    pub chars_translated: u64,
    /// Estimated cumulative cost in USD when this segment was committed.
    pub estimated_cost_usd: f64,
}

/// Return `true` when `version` can be read by this binary without migration.
pub fn is_supported_schema_version(version: u16) -> bool {
    version != 0 && version <= SESSION_LOG_SCHEMA_VERSION
}

/// Convert a [`SystemTime`] to Unix milliseconds, saturating at zero before the epoch.
pub fn system_time_unix_ms(time: SystemTime) -> u64 {
    time.duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().min(u128::from(u64::MAX)) as u64)
        .unwrap_or(0)
}

/// Generate an opaque session id safe for use as a log-file stem.
pub fn generate_session_id(started_at_unix_ms: u64) -> String {
    format!("session-{started_at_unix_ms}-{}", std::process::id())
}

/// Runtime configuration for transcript session recording.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionRecorderConfig {
    /// Whether transcript JSONL recording is enabled.
    pub enabled: bool,
    /// Directory where per-session JSONL files are written when enabled.
    pub directory: PathBuf,
    /// Maximum number of session JSONL files to keep, including the new file.
    pub max_sessions: Option<usize>,
}

impl SessionRecorderConfig {
    /// Create an enabled recorder config using `directory`.
    pub fn enabled(directory: impl Into<PathBuf>) -> Self {
        Self {
            enabled: true,
            directory: directory.into(),
            max_sessions: None,
        }
    }

    /// Create an enabled recorder config and cap retained JSONL files.
    pub fn enabled_with_max_sessions(directory: impl Into<PathBuf>, max_sessions: usize) -> Self {
        Self {
            enabled: true,
            directory: directory.into(),
            max_sessions: Some(max_sessions),
        }
    }

    /// Create a disabled recorder config. The directory is kept for tests and diagnostics.
    pub fn disabled(directory: impl Into<PathBuf>) -> Self {
        Self {
            enabled: false,
            directory: directory.into(),
            max_sessions: None,
        }
    }
}

/// Non-blocking transcript JSONL recorder.
///
/// The hot path calls [`record_segment`](Self::record_segment), which uses
/// `try_send` into a bounded channel. Disk I/O runs on a Tokio task and flushes
/// after each line so a crash cannot leave buffered JSON records unwritten.
pub struct SessionRecorder {
    session_id: Option<String>,
    path: Option<PathBuf>,
    sender: Option<mpsc::Sender<SessionLogRecord>>,
    writer: Option<JoinHandle<()>>,
    last_error: Arc<Mutex<Option<String>>>,
    /// Monotonically non-decreasing count of bytes successfully written and
    /// flushed to disk since the recorder was started (including the header
    /// line).  Zero when the recorder is disabled.
    bytes_written: Arc<AtomicU64>,
}

impl SessionRecorder {
    /// Return a recorder that never creates files and ignores segments.
    pub fn disabled() -> Self {
        Self {
            session_id: None,
            path: None,
            sender: None,
            writer: None,
            last_error: Arc::new(Mutex::new(None)),
            bytes_written: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Start a recorder and write the header line before returning.
    pub async fn start(
        config: SessionRecorderConfig,
        header: SessionHeader,
    ) -> anyhow::Result<Self> {
        if !config.enabled {
            return Ok(Self::disabled());
        }

        fs::create_dir_all(&config.directory).await.map_err(|err| {
            anyhow::anyhow!(
                "failed to create session directory {}: {err}",
                config.directory.display()
            )
        })?;
        if let Some(max_sessions) = config.max_sessions {
            prune_session_logs(&config.directory, max_sessions)?;
        }

        let path = config
            .directory
            .join(session_log_file_name(&header.session_id));
        let session_id = header.session_id.clone();
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&path)
            .await
            .map_err(|err| {
                anyhow::anyhow!("failed to create session log {}: {err}", path.display())
            })?;

        write_record_line(&mut file, &SessionLogRecord::SessionHeader(header.clone()))
            .await
            .map_err(|err| {
                anyhow::anyhow!("failed to write session header {}: {err}", path.display())
            })?;

        let bytes_written = Arc::new(AtomicU64::new(0));
        // Measure and record the bytes from the header write.
        let header_byte_count = record_byte_count(&SessionLogRecord::SessionHeader(header)) as u64;
        bytes_written.fetch_add(header_byte_count, Ordering::Relaxed);

        let (tx, rx) = mpsc::channel(RECORDER_QUEUE_CAPACITY);
        let last_error = Arc::new(Mutex::new(None));
        let writer = tokio::spawn(run_writer(
            file,
            rx,
            Arc::clone(&last_error),
            path.clone(),
            Arc::clone(&bytes_written),
        ));

        Ok(Self {
            session_id: Some(session_id),
            path: Some(path),
            sender: Some(tx),
            writer: Some(writer),
            last_error,
            bytes_written,
        })
    }

    /// Return the JSONL path when recording is enabled.
    pub fn path(&self) -> Option<&Path> {
        self.path.as_deref()
    }

    /// Return the active session id when recording is enabled.
    pub fn session_id(&self) -> Option<&str> {
        self.session_id.as_deref()
    }

    /// Return `true` when this recorder writes transcript files.
    pub fn is_enabled(&self) -> bool {
        self.sender.is_some()
    }

    /// Total bytes successfully written and flushed to disk since the recorder
    /// was started, including the session header.  Monotonically non-decreasing
    /// within a session.  Returns `0` when the recorder is disabled or before
    /// the first write completes.
    pub fn bytes_written(&self) -> u64 {
        self.bytes_written.load(Ordering::Relaxed)
    }

    /// Shared atomic handle for the bytes-written counter.
    ///
    /// Callers that outlive the [`SessionRecorder`] (e.g. the metrics-publisher
    /// task) should clone this `Arc` before the recorder is moved elsewhere.
    pub fn bytes_written_arc(&self) -> Arc<AtomicU64> {
        Arc::clone(&self.bytes_written)
    }

    /// Queue one final transcript segment without waiting for disk I/O.
    pub fn record_segment(&self, segment: TranscriptSegment) -> Result<(), SessionRecorderError> {
        let Some(sender) = &self.sender else {
            return Ok(());
        };

        if let Some(message) = self.last_error() {
            return Err(SessionRecorderError::WriterStopped(message));
        }

        let segment_id = segment.segment_id;
        match sender.try_send(SessionLogRecord::TranscriptSegment(segment)) {
            Ok(()) => Ok(()),
            Err(mpsc::error::TrySendError::Full(_)) => {
                Err(SessionRecorderError::QueueFull { segment_id })
            }
            Err(mpsc::error::TrySendError::Closed(_)) => Err(SessionRecorderError::WriterStopped(
                self.last_error()
                    .unwrap_or_else(|| "session recorder writer stopped".to_string()),
            )),
        }
    }

    /// Return the last asynchronous writer error, if any.
    pub fn last_error(&self) -> Option<String> {
        self.last_error
            .lock()
            .unwrap_or_else(|p| p.into_inner())
            .clone()
    }

    /// Drop the sender and wait for the writer task to flush all queued records.
    pub async fn shutdown(mut self) -> Result<(), SessionRecorderError> {
        drop(self.sender.take());
        if let Some(writer) = self.writer.take() {
            writer
                .await
                .map_err(|err| SessionRecorderError::WriterStopped(err.to_string()))?;
        }
        if let Some(message) = self.last_error() {
            Err(SessionRecorderError::WriterStopped(message))
        } else {
            Ok(())
        }
    }
}

/// Errors surfaced synchronously from the non-blocking recorder handle.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SessionRecorderError {
    /// The bounded writer queue is full; this segment was dropped.
    #[error("session recorder queue is full; dropped transcript segment {segment_id}")]
    QueueFull {
        /// Segment that could not be queued.
        segment_id: u64,
    },
    /// The writer task has stopped, usually after a disk I/O error.
    #[error("session recorder writer stopped: {0}")]
    WriterStopped(String),
}

async fn run_writer(
    mut file: File,
    mut rx: mpsc::Receiver<SessionLogRecord>,
    last_error: Arc<Mutex<Option<String>>>,
    path: PathBuf,
    bytes_written: Arc<AtomicU64>,
) {
    while let Some(record) = rx.recv().await {
        match write_record_line(&mut file, &record).await {
            Ok(n) => {
                bytes_written.fetch_add(n as u64, Ordering::Relaxed);
            }
            Err(err) => {
                let message = format!(
                    "session recorder write failed for {}: {err}",
                    path.display()
                );
                tracing::warn!("{message}");
                *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
                break;
            }
        }
    }

    if let Err(err) = file.flush().await {
        let message = format!(
            "session recorder flush failed for {}: {err}",
            path.display()
        );
        tracing::warn!("{message}");
        *last_error.lock().unwrap_or_else(|p| p.into_inner()) = Some(message);
    }
}

async fn write_record_line(file: &mut File, record: &SessionLogRecord) -> std::io::Result<usize> {
    let mut line = serde_json::to_vec(record).map_err(std::io::Error::other)?;
    line.push(b'\n');
    let len = line.len();
    file.write_all(&line).await?;
    file.flush().await?;
    Ok(len)
}

/// Compute the number of bytes that [`write_record_line`] would write for `record`.
///
/// Used to measure the header write that occurs before the writer task starts.
fn record_byte_count(record: &SessionLogRecord) -> usize {
    serde_json::to_vec(record)
        .map(|v| v.len() + 1) // +1 for the '\n'
        .unwrap_or(0)
}

fn session_log_file_name(session_id: &str) -> String {
    let stem: String = session_id
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect();
    format!("{stem}.jsonl")
}

struct SessionLogCandidate {
    path: PathBuf,
    modified: SystemTime,
}

fn prune_session_logs(directory: &Path, max_sessions: usize) -> anyhow::Result<()> {
    if max_sessions == 0 {
        anyhow::bail!("session recorder max_sessions must be greater than zero");
    }

    let keep_existing = max_sessions.saturating_sub(1);
    let mut logs = Vec::new();
    for entry in std::fs::read_dir(directory).map_err(|err| {
        anyhow::anyhow!(
            "failed to read session directory {}: {err}",
            directory.display()
        )
    })? {
        let entry = entry.map_err(|err| {
            anyhow::anyhow!(
                "failed to read session directory entry {}: {err}",
                directory.display()
            )
        })?;
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("jsonl") {
            continue;
        }
        let metadata = entry.metadata().map_err(|err| {
            anyhow::anyhow!("failed to inspect session log {}: {err}", path.display())
        })?;
        if !metadata.is_file() {
            continue;
        }
        logs.push(SessionLogCandidate {
            path,
            modified: metadata.modified().unwrap_or(UNIX_EPOCH),
        });
    }

    if logs.len() <= keep_existing {
        return Ok(());
    }

    logs.sort_by(|a, b| {
        a.modified
            .cmp(&b.modified)
            .then_with(|| a.path.cmp(&b.path))
    });
    let remove_count = logs.len() - keep_existing;
    for candidate in logs.into_iter().take(remove_count) {
        std::fs::remove_file(&candidate.path).map_err(|err| {
            anyhow::anyhow!(
                "failed to prune old session log {}: {err}",
                candidate.path.display()
            )
        })?;
    }
    Ok(())
}

// ── Session/audio pairing contract ───────────────────────────────────────────

/// Extract the session-id stem from a JSONL session-log path.
///
/// Returns the file stem (the filename without its extension) as a `&str`, or
/// `None` when the path has no filename component or the stem contains
/// non-UTF-8 bytes.
///
/// The returned value is the sanitized session-id encoded by
/// [`session_log_file_name`] — every character outside `[A-Za-z0-9\-_]` is
/// replaced with `_` at write time.  The same sanitization rule is applied by
/// `audio::archive::session_wav_file_name`, so two artifact files written from
/// the same `session_id` always share an identical stem.  Use
/// [`check_session_pairing`] to verify that a JSONL path and a WAV path belong
/// to the same recording session.
pub fn session_id_from_jsonl_path(path: &Path) -> Option<&str> {
    path.file_stem()?.to_str()
}

/// Error returned when a JSONL transcript and a WAV audio-archive path-pair do
/// not share the same session-id stem.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SessionPairingError {
    /// The JSONL path yields no decodable file stem.
    #[error("JSONL path has no valid UTF-8 file stem: {path}")]
    NoJsonlStem {
        /// Display form of the offending path.
        path: String,
    },
    /// The WAV path yields no decodable file stem.
    #[error("WAV path has no valid UTF-8 file stem: {path}")]
    NoWavStem {
        /// Display form of the offending path.
        path: String,
    },
    /// The two stems differ; the paths belong to different sessions.
    #[error("session artifact mismatch: JSONL stem `{jsonl_stem}` != WAV stem `{wav_stem}`")]
    Mismatch {
        /// Stem extracted from the JSONL path.
        jsonl_stem: String,
        /// Stem extracted from the WAV path.
        wav_stem: String,
    },
}

/// Verify that `jsonl_path` and `wav_path` are paired artifacts from the same
/// recording session.
///
/// # Pairing contract
///
/// Both [`session_log_file_name`] (JSONL writer) and `session_wav_file_name`
/// (WAV writer in `audio::archive`) apply an identical sanitization rule:
/// keep ASCII alphanumeric characters, `-`, and `_`; replace every other byte
/// with `_`.  Given the same `session_id` string, both functions produce an
/// identical file stem.  Two artifact paths are therefore paired if and only if
/// their file stems are equal.
///
/// Returns `Ok(stem)` — the shared, sanitized session-id — when the pair
/// matches.  Returns a [`SessionPairingError`] that identifies the specific
/// mismatch so callers can reject artifact pairs deterministically.
///
/// # Example
///
/// ```ignore
/// use std::path::Path;
///
/// // Matching pair produced from the same session-id:
/// let stem = check_session_pairing(
///     Path::new("sessions/session-1710000000000-42.jsonl"),
///     Path::new("audio/session-1710000000000-42.wav"),
/// )
/// .unwrap();
/// assert_eq!(stem, "session-1710000000000-42");
/// ```
pub fn check_session_pairing<'a>(
    jsonl_path: &'a Path,
    wav_path: &Path,
) -> Result<&'a str, SessionPairingError> {
    let jsonl_stem = jsonl_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| SessionPairingError::NoJsonlStem {
            path: jsonl_path.display().to_string(),
        })?;
    let wav_stem = wav_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| SessionPairingError::NoWavStem {
            path: wav_path.display().to_string(),
        })?;
    if jsonl_stem != wav_stem {
        return Err(SessionPairingError::Mismatch {
            jsonl_stem: jsonl_stem.to_string(),
            wav_stem: wav_stem.to_string(),
        });
    }
    Ok(jsonl_stem)
}

// ── Export helpers ────────────────────────────────────────────────────────────

/// Format a millisecond offset as an SRT timestamp: `HH:MM:SS,mmm`.
fn ms_to_srt_timestamp(ms: u64) -> String {
    let total_secs = ms / 1_000;
    let millis = ms % 1_000;
    let secs = total_secs % 60;
    let total_mins = total_secs / 60;
    let mins = total_mins % 60;
    let hours = total_mins / 60;
    format!("{hours:02}:{mins:02}:{secs:02},{millis:03}")
}

/// Render a slice of [`TranscriptSegment`]s as a valid SRT string.
///
/// Each segment becomes one numbered subtitle block using `audio_start_ms` and
/// `audio_end_ms` as the cue timestamps.  Both source and target text are
/// placed on separate lines inside the cue body.  An empty slice produces an
/// empty string (zero cue blocks), which is a valid SRT file.
pub fn export_srt(segments: &[TranscriptSegment]) -> String {
    let mut out = String::new();
    for (i, seg) in segments.iter().enumerate() {
        let index = i + 1;
        let start = ms_to_srt_timestamp(seg.audio_start_ms);
        let end = ms_to_srt_timestamp(seg.audio_end_ms);
        out.push_str(&format!(
            "{index}\n{start} --> {end}\n{src}\n{tgt}\n\n",
            src = seg.source_text,
            tgt = seg.target_text,
        ));
    }
    out
}

/// Render a slice of [`TranscriptSegment`]s as a plain-text bilingual transcript.
///
/// Each segment is separated by a blank line.  Source text is prefixed with
/// `[SRC]` and target text with `[TGT]`.  An empty slice produces an empty
/// string, which is a valid TXT export.
pub fn export_txt(segments: &[TranscriptSegment]) -> String {
    let mut out = String::new();
    for (i, seg) in segments.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&format!(
            "[SRC] {}\n[TGT] {}\n",
            seg.source_text, seg.target_text,
        ));
    }
    out
}

/// Errors returned while loading transcript segments for export.
#[derive(Debug, Error)]
pub enum SessionExportError {
    /// A JSONL record could not be parsed as the current session schema.
    #[error("failed to parse session log line {line}: {source}")]
    InvalidJson {
        /// One-based JSONL line number.
        line: usize,
        /// Underlying JSON parse or schema-version error.
        #[source]
        source: serde_json::Error,
    },
}

/// Extract transcript segments from a session JSONL string for replay/export.
///
/// Header records are ignored and blank lines are skipped. Future schema
/// versions are rejected by the record deserializer instead of being guessed.
pub fn transcript_segments_from_jsonl(
    contents: &str,
) -> Result<Vec<TranscriptSegment>, SessionExportError> {
    let mut segments = Vec::new();
    for (index, line) in contents.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let record: SessionLogRecord =
            serde_json::from_str(line).map_err(|source| SessionExportError::InvalidJson {
                line: index + 1,
                source,
            })?;
        if let SessionLogRecord::TranscriptSegment(segment) = record {
            segments.push(segment);
        }
    }
    Ok(segments)
}

// ── Session replay ────────────────────────────────────────────────────────────

/// Parse transcript segments from a JSONL string, skipping malformed lines.
///
/// Unlike [`transcript_segments_from_jsonl`], malformed JSON/record lines are
/// logged with [`tracing::warn!`] and counted in the returned `skipped_count`.
/// Records with unsupported schema versions still fail the replay load so
/// callers do not silently ignore data from a future format.
///
/// The header record is silently ignored (not counted as skipped).
/// Blank lines are silently ignored.
///
/// # Errors
///
/// Returns [`SessionReplayError::UnsupportedSchema`] when a valid JSON record
/// carries a schema version outside this binary's supported range.
pub fn transcript_segments_from_jsonl_lenient(
    contents: &str,
) -> Result<(Vec<TranscriptSegment>, usize), SessionReplayError> {
    let mut segments = Vec::new();
    let mut skipped = 0usize;
    for (index, line) in contents.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        match serde_json::from_str::<SessionLogRecord>(line) {
            Ok(SessionLogRecord::TranscriptSegment(seg)) => segments.push(seg),
            Ok(SessionLogRecord::SessionHeader(_)) => {}
            Err(err) => {
                if let Some(version) = unsupported_schema_version(line) {
                    return Err(SessionReplayError::UnsupportedSchema {
                        line: index + 1,
                        version,
                    });
                }
                tracing::warn!(
                    line = index + 1,
                    error = %err,
                    "skipping malformed session log line during replay"
                );
                skipped += 1;
            }
        }
    }
    Ok((segments, skipped))
}

/// Errors returned while loading a session for replay.
#[derive(Debug, Error)]
pub enum SessionReplayError {
    /// A JSON record uses a schema version this binary must not guess how to read.
    #[error(
        "unsupported session log schema version {version} on replay line {line}; supported range is 1..={SESSION_LOG_SCHEMA_VERSION}"
    )]
    UnsupportedSchema {
        /// One-based JSONL line number.
        line: usize,
        /// Unsupported schema version found in that line.
        version: u64,
    },
}

fn unsupported_schema_version(line: &str) -> Option<u64> {
    let value: serde_json::Value = serde_json::from_str(line).ok()?;
    let version = value.get("schema_version")?.as_u64()?;
    if version == 0 || version > u64::from(SESSION_LOG_SCHEMA_VERSION) {
        Some(version)
    } else {
        None
    }
}

/// Replay engine for a session JSONL log.
///
/// Loads all [`TranscriptSegment`]s from a session file, tracks a cursor
/// through them, and supports deterministic pause/resume so the position is
/// preserved while paused.
///
/// # Replay contract
///
/// - Malformed lines are skipped with a `tracing::warn!` and counted in
///   [`skipped_count`](Self::skipped_count).
/// - Unsupported future schema versions are still rejected (the underlying
///   deserializer enforces the version gate).
/// - [`next_segment`](Self::next_segment) returns `None` when paused **or**
///   when all segments have been yielded.  The cursor does not advance while
///   paused, so resuming picks up exactly where the session was paused.
#[derive(Debug)]
pub struct SessionReplayer {
    segments: VecDeque<TranscriptSegment>,
    /// Total number of valid segments loaded before replay began.
    total_segments: usize,
    /// Zero-based index of the next original segment to yield.
    cursor: usize,
    paused: bool,
    skipped_count: usize,
}

impl SessionReplayer {
    /// Build a replayer by parsing a session JSONL string.
    ///
    /// Malformed lines are skipped with a warning; see
    /// [`transcript_segments_from_jsonl_lenient`].
    pub fn load(contents: &str) -> Result<Self, SessionReplayError> {
        let (segments, skipped_count) = transcript_segments_from_jsonl_lenient(contents)?;
        let total_segments = segments.len();
        Ok(Self {
            segments: VecDeque::from(segments),
            total_segments,
            cursor: 0,
            paused: false,
            skipped_count,
        })
    }

    /// Advance the cursor and return the next segment.
    ///
    /// Returns `None` when the replayer is paused or all segments have been
    /// yielded.  The cursor is **not** incremented while paused, so a
    /// subsequent call after [`resume`](Self::resume) returns the same segment.
    pub fn next_segment(&mut self) -> Option<TranscriptSegment> {
        if self.paused {
            return None;
        }
        let seg = self.segments.pop_front()?;
        self.cursor += 1;
        Some(seg)
    }

    /// Pause replay.  Future calls to [`next_segment`](Self::next_segment)
    /// return `None` until [`resume`](Self::resume) is called.
    pub fn pause(&mut self) {
        self.paused = true;
    }

    /// Resume replay from the position where it was paused.
    pub fn resume(&mut self) {
        self.paused = false;
    }

    /// Return `true` when replay is currently paused.
    pub fn is_paused(&self) -> bool {
        self.paused
    }

    /// Return `true` when all segments have been yielded.
    pub fn is_done(&self) -> bool {
        self.segments.is_empty()
    }

    /// Zero-based index of the next segment to yield.
    pub fn cursor(&self) -> usize {
        self.cursor
    }

    /// Total number of valid [`TranscriptSegment`]s loaded from the JSONL.
    pub fn segment_count(&self) -> usize {
        self.total_segments
    }

    /// Number of lines that were skipped due to parse errors.
    pub fn skipped_count(&self) -> usize {
        self.skipped_count
    }
}

fn deserialize_supported_schema_version<'de, D>(deserializer: D) -> Result<u16, D::Error>
where
    D: Deserializer<'de>,
{
    let version = u16::deserialize(deserializer)?;
    if is_supported_schema_version(version) {
        Ok(version)
    } else {
        Err(serde::de::Error::custom(format!(
            "unsupported session log schema version {version}; supported range is 1..={SESSION_LOG_SCHEMA_VERSION}"
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn version_gate_accepts_current_and_rejects_zero_or_future() {
        assert!(is_supported_schema_version(SESSION_LOG_SCHEMA_VERSION));
        assert!(!is_supported_schema_version(0));
        assert!(!is_supported_schema_version(
            SESSION_LOG_SCHEMA_VERSION.saturating_add(1)
        ));
    }

    #[test]
    fn session_log_file_name_sanitizes_path_separators() {
        assert_eq!(
            session_log_file_name("session/..\\bad:name"),
            "session____bad_name.jsonl"
        );
    }

    #[tokio::test]
    async fn disabled_recorder_creates_no_files() {
        let temp = TempDir::new().unwrap();
        let sessions_dir = temp.path().join("sessions");
        let header = test_header("disabled-session");

        let recorder = SessionRecorder::start(
            SessionRecorderConfig::disabled(sessions_dir.clone()),
            header,
        )
        .await
        .unwrap();
        recorder.record_segment(test_segment(1)).unwrap();
        recorder.shutdown().await.unwrap();

        assert!(
            !sessions_dir.exists(),
            "disabled recorder must not create a sessions directory"
        );
    }

    #[tokio::test]
    async fn enabled_recorder_writes_valid_jsonl() {
        let temp = TempDir::new().unwrap();
        let sessions_dir = temp.path().join("sessions");
        let recorder = SessionRecorder::start(
            SessionRecorderConfig::enabled(sessions_dir.clone()),
            test_header("enabled-session"),
        )
        .await
        .unwrap();
        let path = recorder.path().unwrap().to_path_buf();

        for id in 1..=3 {
            recorder.record_segment(test_segment(id)).unwrap();
        }
        recorder.shutdown().await.unwrap();

        let raw = std::fs::read_to_string(path).unwrap();
        let records: Vec<SessionLogRecord> = raw
            .lines()
            .map(|line| serde_json::from_str(line).unwrap())
            .collect();

        assert_eq!(records.len(), 4, "header plus three transcript records");
        assert!(matches!(records[0], SessionLogRecord::SessionHeader(_)));
        assert_eq!(
            records
                .iter()
                .filter(|record| matches!(record, SessionLogRecord::TranscriptSegment(_)))
                .count(),
            3
        );
    }

    #[tokio::test]
    async fn enabled_recorder_prunes_old_session_logs_to_max_sessions() {
        let temp = TempDir::new().unwrap();
        let sessions_dir = temp.path().join("sessions");
        std::fs::create_dir_all(&sessions_dir).unwrap();
        std::fs::write(sessions_dir.join("old-a.jsonl"), "{}\n").unwrap();
        std::fs::write(sessions_dir.join("old-b.jsonl"), "{}\n").unwrap();
        std::fs::write(sessions_dir.join("old-c.jsonl"), "{}\n").unwrap();

        let recorder = SessionRecorder::start(
            SessionRecorderConfig::enabled_with_max_sessions(sessions_dir.clone(), 2),
            test_header("new-session"),
        )
        .await
        .unwrap();
        recorder.shutdown().await.unwrap();

        let jsonl_count = std::fs::read_dir(&sessions_dir)
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("jsonl"))
            .count();

        assert_eq!(jsonl_count, 2, "new session plus one retained old log");
        assert!(sessions_dir.join("new-session.jsonl").exists());
    }

    // ── Issue #393: bytes_written counter tests ────────────────────────────────

    #[test]
    fn disabled_recorder_bytes_written_is_zero() {
        let recorder = SessionRecorder::disabled();
        assert_eq!(recorder.bytes_written(), 0);
    }

    #[tokio::test]
    async fn enabled_recorder_bytes_written_increases_after_writes() {
        let temp = TempDir::new().expect("create tempdir");
        let sessions_dir = temp.path().join("sessions");
        let recorder = SessionRecorder::start(
            SessionRecorderConfig::enabled(sessions_dir.clone()),
            test_header("bytes-test"),
        )
        .await
        .expect("start recorder");

        // After start, the header has already been written and counted.
        let after_header = recorder.bytes_written();
        assert!(
            after_header > 0,
            "bytes_written must be > 0 after header write; got {after_header}"
        );

        // Clone the Arc before moving recorder into shutdown().
        let arc = recorder.bytes_written_arc();

        // Record a segment and wait for the writer task to flush.
        recorder
            .record_segment(test_segment(1))
            .expect("record segment");
        recorder.shutdown().await.expect("shutdown recorder");

        let after_segment = arc.load(std::sync::atomic::Ordering::Relaxed);
        assert!(
            after_segment >= after_header,
            "bytes_written must not decrease; header={after_header}, after={after_segment}"
        );
        assert!(
            after_segment > after_header,
            "bytes_written must increase after a successful segment write"
        );
    }

    #[tokio::test]
    async fn bytes_written_matches_actual_file_size() {
        let temp = TempDir::new().expect("create tempdir");
        let sessions_dir = temp.path().join("sessions");
        let recorder = SessionRecorder::start(
            SessionRecorderConfig::enabled(sessions_dir.clone()),
            test_header("file-size-test"),
        )
        .await
        .expect("start recorder");
        let path = recorder.path().expect("recorder has path").to_path_buf();
        let arc = recorder.bytes_written_arc();

        recorder
            .record_segment(test_segment(1))
            .expect("record segment 1");
        recorder
            .record_segment(test_segment(2))
            .expect("record segment 2");
        recorder.shutdown().await.expect("shutdown recorder");

        let reported = arc.load(std::sync::atomic::Ordering::Relaxed);
        let actual = std::fs::metadata(&path).expect("read file metadata").len();
        assert_eq!(
            reported, actual,
            "bytes_written() must equal the actual file size on disk"
        );
    }

    #[tokio::test]
    async fn bytes_written_arc_is_shared_with_internal_counter() {
        let temp = TempDir::new().expect("create tempdir");
        let sessions_dir = temp.path().join("sessions");
        let recorder = SessionRecorder::start(
            SessionRecorderConfig::enabled(sessions_dir.clone()),
            test_header("arc-share-test"),
        )
        .await
        .expect("start recorder");

        let arc = recorder.bytes_written_arc();
        let after_header = arc.load(std::sync::atomic::Ordering::Relaxed);
        assert!(
            after_header > 0,
            "cloned Arc must reflect header bytes; got {after_header}"
        );

        recorder
            .record_segment(test_segment(1))
            .expect("record segment");
        recorder.shutdown().await.expect("shutdown recorder");

        let after_segment = arc.load(std::sync::atomic::Ordering::Relaxed);
        assert!(
            after_segment > after_header,
            "Arc must reflect segment bytes written through the shared atomic"
        );
    }

    fn test_header(session_id: &str) -> SessionHeader {
        SessionHeader {
            schema_version: SESSION_LOG_SCHEMA_VERSION,
            session_id: session_id.to_string(),
            app_version: "test".to_string(),
            started_at_unix_ms: 1_710_000_000_000,
            source_language: "ja-JP".to_string(),
            target_language: "vi".to_string(),
            stt_provider: "google".to_string(),
            mt_provider: "google".to_string(),
            tts_enabled: false,
            capture_device: None,
        }
    }

    fn test_segment(segment_id: u64) -> TranscriptSegment {
        TranscriptSegment {
            schema_version: SESSION_LOG_SCHEMA_VERSION,
            session_id: "enabled-session".to_string(),
            segment_id,
            sequence_number: segment_id,
            finalized_at_unix_ms: 1_710_000_000_000 + segment_id,
            audio_start_ms: segment_id * 1_000,
            audio_end_ms: segment_id * 1_000 + 900,
            source_text: format!("source-{segment_id}"),
            target_text: format!("target-{segment_id}"),
            source_language: "ja-JP".to_string(),
            detected_source_language: Some("ja".to_string()),
            target_language: "vi".to_string(),
            stt_provider: "google".to_string(),
            mt_provider: "google".to_string(),
            stt_confidence: Some(0.9),
            stt_is_final: true,
            stt_latency_ms: Some(100),
            mt_latency_ms: Some(50),
            end_to_end_latency_ms: Some(200),
            audio_seconds_sent: 1.0,
            chars_translated: 10,
            estimated_cost_usd: 0.01,
        }
    }

    /// Build a minimal JSONL string with the given segments for replay tests.
    fn replay_jsonl(segments: &[TranscriptSegment]) -> String {
        let header = SessionLogRecord::SessionHeader(test_header("replay-test"));
        let mut out = serde_json::to_string(&header).unwrap();
        out.push('\n');
        for seg in segments {
            out.push_str(
                &serde_json::to_string(&SessionLogRecord::TranscriptSegment(seg.clone())).unwrap(),
            );
            out.push('\n');
        }
        out
    }

    // ── SessionReplayer unit tests ─────────────────────────────────────────────

    #[test]
    fn replayer_loads_five_segments_in_order() {
        let segs: Vec<_> = (1..=5).map(test_segment).collect();
        let jsonl = replay_jsonl(&segs);
        let mut replayer = SessionReplayer::load(&jsonl).unwrap();

        assert_eq!(replayer.segment_count(), 5);
        assert_eq!(replayer.skipped_count(), 0);

        for expected_id in 1u64..=5 {
            let seg = replayer
                .next_segment()
                .expect("should yield segment in order");
            assert_eq!(
                seg.segment_id, expected_id,
                "segment at position {expected_id} must appear in order"
            );
        }
        assert!(
            replayer.is_done(),
            "replayer must report done after all segments"
        );
        assert!(
            replayer.next_segment().is_none(),
            "next after done must be None"
        );
    }

    #[test]
    fn replayer_skips_malformed_lines_and_counts_them() {
        let good_seg = test_segment(42);
        let header_line =
            serde_json::to_string(&SessionLogRecord::SessionHeader(test_header("t"))).unwrap();
        let good_line =
            serde_json::to_string(&SessionLogRecord::TranscriptSegment(good_seg.clone())).unwrap();

        let jsonl = format!("{header_line}\nnot_valid_json\n{good_line}\n{{\"bad\":true}}\n");
        let mut replayer = SessionReplayer::load(&jsonl).unwrap();

        assert_eq!(
            replayer.skipped_count(),
            2,
            "two malformed lines must be counted"
        );
        assert_eq!(replayer.segment_count(), 1);

        let yielded = replayer.next_segment().unwrap();
        assert_eq!(yielded.segment_id, 42);
        assert!(replayer.is_done());
    }

    #[test]
    fn replayer_pause_preserves_cursor_and_resume_continues() {
        let segs: Vec<_> = (1..=5).map(test_segment).collect();
        let jsonl = replay_jsonl(&segs);
        let mut replayer = SessionReplayer::load(&jsonl).unwrap();

        // Yield the first two segments (ids 1, 2).
        assert_eq!(replayer.next_segment().unwrap().segment_id, 1);
        assert_eq!(replayer.next_segment().unwrap().segment_id, 2);
        assert_eq!(replayer.cursor(), 2);

        // Pause: cursor must not advance.
        replayer.pause();
        assert!(replayer.is_paused());
        assert!(
            replayer.next_segment().is_none(),
            "next_segment while paused must return None"
        );
        assert_eq!(replayer.cursor(), 2, "cursor must not change while paused");

        // Multiple paused calls are idempotent.
        assert!(replayer.next_segment().is_none());
        assert_eq!(replayer.cursor(), 2);

        // Resume: must continue from exactly position 2 (segment id 3).
        replayer.resume();
        assert!(!replayer.is_paused());
        assert_eq!(
            replayer.next_segment().unwrap().segment_id,
            3,
            "first segment after resume must be the one at the saved cursor"
        );
        assert_eq!(replayer.cursor(), 3);
        assert!(
            !replayer.is_done(),
            "replayer must not report done until every queued segment is yielded"
        );

        // Remaining segments 4 and 5 are still available.
        assert_eq!(replayer.next_segment().unwrap().segment_id, 4);
        assert_eq!(replayer.next_segment().unwrap().segment_id, 5);
        assert!(replayer.is_done());
    }

    #[test]
    fn replayer_ignores_blank_lines_and_header() {
        let seg = test_segment(7);
        let header_line =
            serde_json::to_string(&SessionLogRecord::SessionHeader(test_header("t2"))).unwrap();
        let seg_line = serde_json::to_string(&SessionLogRecord::TranscriptSegment(seg)).unwrap();
        let jsonl = format!("\n{header_line}\n\n{seg_line}\n\n");
        let replayer = SessionReplayer::load(&jsonl).unwrap();

        assert_eq!(replayer.segment_count(), 1);
        assert_eq!(
            replayer.skipped_count(),
            0,
            "header and blank lines must not count as skipped"
        );
    }

    #[test]
    fn replayer_rejects_future_schema_version() {
        let line =
            serde_json::to_string(&SessionLogRecord::TranscriptSegment(test_segment(9))).unwrap();
        let future_version = u64::from(SESSION_LOG_SCHEMA_VERSION) + 1;
        let line = line.replace(
            &format!("\"schema_version\":{}", SESSION_LOG_SCHEMA_VERSION),
            &format!("\"schema_version\":{future_version}"),
        );

        let err = transcript_segments_from_jsonl_lenient(&line).unwrap_err();
        assert!(
            matches!(
                err,
                SessionReplayError::UnsupportedSchema {
                    line: 1,
                    version
                } if version == future_version
            ),
            "future schema version must fail replay load, got {err:?}"
        );
    }
}
