//! Versioned JSONL schema for persisted translation sessions.
//!
//! Each session log is newline-delimited JSON.  The first line is a
//! [`SessionLogRecord::SessionHeader`] and each later subtitle entry is a
//! [`SessionLogRecord::TranscriptSegment`].  Every record carries
//! [`SESSION_LOG_SCHEMA_VERSION`] so replay/export code can reject or migrate
//! future formats explicitly instead of guessing.
//!
//! Versioning rules:
//! - Additive optional fields keep the same major schema version.
//! - Renaming, removing, or changing the meaning of a required field requires a
//!   new schema version and a migration path.
//! - Readers must reject records with versions greater than
//!   [`SESSION_LOG_SCHEMA_VERSION`] until a migration is implemented.

#![allow(dead_code)]

/// HC-03: session recorder supervisor stub (classification is in crate::config::recorder_supervisor).
pub mod supervisor;

pub mod export;
#[allow(unused_imports)]
pub use export::{export_srt, export_txt, transcript_segments_from_jsonl, SessionExportError};

pub mod pairing;
#[allow(unused_imports)]
pub(crate) use pairing::looks_like_segment_stem;
#[allow(unused_imports)]
pub use pairing::{check_session_pairing, session_id_from_jsonl_path, SessionPairingError};

pub mod replay;
#[allow(unused_imports)]
pub use replay::{transcript_segments_from_jsonl_lenient, SessionReplayError, SessionReplayer};

// #484 STD-02 RQ-B8: recorder cluster extracted from this file. The public
// surface (SessionRecorder, SessionRecorderConfig, SessionRecorderError) is
// re-exported below so callers and existing tests keep working unchanged.
mod recorder;
mod recorder_writer;

#[allow(unused_imports)]
pub use recorder::{SessionRecorder, SessionRecorderConfig, SessionRecorderError};

// Internal helpers exposed through the session namespace solely for the tests
// mounted at this module level (recorder_tests, replayer_slot_tests).
#[cfg(test)]
#[allow(unused_imports)]
pub(crate) use recorder_writer::{segment_file_name, session_log_file_name, validate_slot_suffix};

use serde::{Deserialize, Deserializer, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// Current JSONL session-log schema version.
pub const SESSION_LOG_SCHEMA_VERSION: u16 = 1;

/// A single line in a persisted session JSONL file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "record_type", rename_all = "snake_case")]
pub enum SessionLogRecord {
    /// File/session metadata.  This must be the first record in a new log.
    SessionHeader(SessionHeader),
    /// One committed bilingual subtitle segment.
    TranscriptSegment(TranscriptSegment),
}

impl SessionLogRecord {
    /// Return the schema version carried by this record.
    pub fn schema_version(&self) -> u16 {
        match self {
            Self::SessionHeader(header) => header.schema_version,
            Self::TranscriptSegment(segment) => segment.schema_version,
        }
    }
}

/// Metadata that describes one translation session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SessionHeader {
    /// Schema version used by every record in this file.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Stable opaque session identifier generated by the writer.
    pub session_id: String,
    /// Application version that created the session log.
    pub app_version: String,
    /// Unix timestamp in milliseconds when capture started.
    pub started_at_unix_ms: u64,
    /// Source language spoken in the meeting, as a BCP-47 tag.
    pub source_language: String,
    /// Target subtitle language, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider selected for this session.
    pub stt_provider: String,
    /// Machine-translation provider selected for this session.
    pub mt_provider: String,
    /// Whether translated audio playback was enabled at session start.
    pub tts_enabled: bool,
    /// Capture device label if one was selected; absent means Windows default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capture_device: Option<String>,
    /// Human-readable slot label for dual-slot sessions ("A" for slot A, "B" for slot B).
    /// Absent in single-slot sessions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slot_label: Option<String>,
    /// Machine-readable slot identifier for dual-slot sessions.
    ///
    /// This matches the lowercase filename suffix used by the recorder
    /// (for example, built-in dual mode uses `"a"` and `"b"`).
    /// Absent in single-slot sessions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slot_id: Option<String>,
}

/// One committed bilingual subtitle segment and its replay/export metadata.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TranscriptSegment {
    /// Schema version used by this segment.
    #[serde(deserialize_with = "deserialize_supported_schema_version")]
    pub schema_version: u16,
    /// Session identifier matching the header record.
    pub session_id: String,
    /// Monotonic segment identifier assigned after final subtitle promotion.
    pub segment_id: u64,
    /// Pipeline sequence number for the STT audio window or streaming segment.
    pub sequence_number: u64,
    /// Unix timestamp in milliseconds when the source text became final.
    pub finalized_at_unix_ms: u64,
    /// Start of the source audio span relative to session start, in milliseconds.
    pub audio_start_ms: u64,
    /// End of the source audio span relative to session start, in milliseconds.
    pub audio_end_ms: u64,
    /// Recognized source-language text.
    pub source_text: String,
    /// Translated target-language text.
    pub target_text: String,
    /// Source language for this segment, as a BCP-47 tag.
    pub source_language: String,
    /// Source language detected by the MT provider, when available.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detected_source_language: Option<String>,
    /// Target language for this segment, as a BCP-47 tag.
    pub target_language: String,
    /// Speech-to-text provider that produced `source_text`.
    pub stt_provider: String,
    /// Machine-translation provider that produced `target_text`.
    pub mt_provider: String,
    /// STT confidence in the range `[0.0, 1.0]`, when provided by the backend.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_confidence: Option<f32>,
    /// STT final/interim flag captured for audit and replay diagnostics.
    pub stt_is_final: bool,
    /// STT latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stt_latency_ms: Option<u64>,
    /// Machine-translation latency for this segment in milliseconds, when measured.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mt_latency_ms: Option<u64>,
    /// End-to-end latency from audio submission to translated subtitle display.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub end_to_end_latency_ms: Option<u64>,
    /// Cumulative audio seconds sent to STT when this segment was committed.
    pub audio_seconds_sent: f64,
    /// Cumulative source characters sent to MT when this segment was committed.
    pub chars_translated: u64,
    /// Estimated cumulative cost in USD when this segment was committed.
    pub estimated_cost_usd: f64,
}

/// Return `true` when `version` can be read by this binary without migration.
pub fn is_supported_schema_version(version: u16) -> bool {
    version != 0 && version <= SESSION_LOG_SCHEMA_VERSION
}

/// Convert a [`SystemTime`] to Unix milliseconds, saturating at zero before the epoch.
pub fn system_time_unix_ms(time: SystemTime) -> u64 {
    time.duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_millis().min(u128::from(u64::MAX)) as u64)
        .unwrap_or(0)
}

/// Generate an opaque session id safe for use as a log-file stem.
pub fn generate_session_id(started_at_unix_ms: u64) -> String {
    format!("session-{started_at_unix_ms}-{}", std::process::id())
}

fn deserialize_supported_schema_version<'de, D>(deserializer: D) -> Result<u16, D::Error>
where
    D: Deserializer<'de>,
{
    let version = u16::deserialize(deserializer)?;
    if is_supported_schema_version(version) {
        Ok(version)
    } else {
        Err(serde::de::Error::custom(format!(
            "unsupported session log schema version {version}; supported range is 1..={SESSION_LOG_SCHEMA_VERSION}"
        )))
    }
}

#[cfg(test)]
#[path = "recorder_tests.rs"]
mod recorder_tests;

#[cfg(test)]
#[path = "replayer_slot_tests.rs"]
mod replayer_slot_tests;
